Contributing
JeanPhilippeKernel/RendererEngine pull request #118
Opened 2021-11-08 11:45 UTC by JFancis

Hi, 
I just finished writing the contribution file Beta

2021-11-10 21:04 UTC, JeanPhilippeKernel requested changes

2021-11-10 21:04 UTC, JeanPhilippeKernel commented on Contributing.md
> +### Attribution
Can we remove this attribution part ??

2021-11-10 21:04 UTC, JeanPhilippeKernel commented on Contributing.md
> +Z-ENGINE - Contributing
I don't think we need it so you can remove it

2021-11-10 21:04 UTC, JeanPhilippeKernel commented on Contributing.md
> +# Contributing
nit : Contributing to ZEngine

2021-11-10 21:04 UTC, JeanPhilippeKernel commented on Contributing.md
> +## Code of Conduct
We have to remove/move the Code of conduct part to another doc  and maybe reference it here as a bullet point  of the pull request section

2021-11-11 09:55 UTC, JFancis reviewed
the contributing file has been updated,
and Code Conduct Created.

2021-11-11 19:43 UTC, JeanPhilippeKernel approved these changes

2021-11-11 19:44 UTC, merged

2021-11-11 21:51 UTC, JeanPhilippeKernel commented
Thanks for your help  !! 😉🎉