Log UI
JeanPhilippeKernel/RendererEngine pull request #405
Opened 2024-12-10 17:57 UTC by jnyfah

2025-01-04 21:59 UTC, JeanPhilippeKernel requested changes

2025-01-04 21:59 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +                if (std::strlen(m_search_buffer) > 0)
you should use secure_strlen

2025-01-04 21:59 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +            for (const auto& message : m_log_queue)
can we switch m_log_queue type from vector to ThreadSafeQueue ? and pop available log message per frame?
this will reduce the pression on this component to render content

2025-01-04 21:59 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (std::strlen(m_search_buffer) > 0)
you should use secure_strlen

2025-01-04 21:59 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (m_is_copy_button_pressed = ImGui::Button("Copy"))
is that mean we no longer need m_is_copy_button_pressed

2025-01-04 21:59 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.h
>          bool                                      m_is_clear_button_pressed{false};
to delete ?

2025-01-06 22:26 UTC, jnyfah commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (m_is_copy_button_pressed = ImGui::Button("Copy"))
I think we still need it

2025-01-06 22:26 UTC, jnyfah commented on Tetragrama/Components/LogUIComponent.h
>          bool                                      m_is_clear_button_pressed{false};
nope

2025-01-07 09:54 UTC, JeanPhilippeKernel requested changes

2025-01-07 09:54 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.h
>          bool                                      m_is_clear_button_pressed{false};
but I don't see where you use it.

2025-01-07 09:54 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (m_is_copy_button_pressed = ImGui::Button("Copy"))
the code can be simplified as
```
if(ImGui::Button("Copy"))
```

2025-01-07 14:24 UTC, jnyfah commented on Tetragrama/Components/LogUIComponent.h
>          bool                                      m_is_clear_button_pressed{false};
oh yes sorry this will be delete

2025-01-07 14:27 UTC, jnyfah commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (m_is_copy_button_pressed = ImGui::Button("Copy"))
that wouldn't work because `if(ImGui::Button("Copy"))` creates a new button and calling it twice on one frame would not be ideal 
see lines 60 and 101

2025-01-07 14:41 UTC, JeanPhilippeKernel commented on Tetragrama/Components/LogUIComponent.cpp
> +        if (m_is_copy_button_pressed = ImGui::Button("Copy"))
Oh okay, I see !

2025-01-07 14:51 UTC, JeanPhilippeKernel approved these changes

2025-01-07 14:51 UTC, merged